### ISSUE TITLE
Add a way to validate in a release PR that new sections exist in changelogs for bumped packages and that versions match

### ISSUE THREAD

**Issue by mcmire** [MetaMask/create-release-branch#111]
Add a `validate` command that can be run on a release branch which verifies that for each package that is being bumped in a monorepo, there is a new section present in the package's changelog for that version, and that the version of this section matches the new version in `package.json`.

**Comment by desi** [comment]
@mcmire based on feedback in planning take a look at auto changelog to see if it does this.

**Comment by mcmire** [comment]
It turns out that `auto-changelog` does check this already. If you bump the version of a package but that version does not correspond to a section in that package's changelog, then running `yarn changelog:validate` for that package will produce the error "Changelog is invalid: Current version missing from changelog: '0.0.0'". That satisfies what I was looking for, so I'll close this.
