### ISSUE TITLE
Package bumps are not applied to dependencies in Yarn Modern monorepos with constraints on dependencies

### ISSUE THREAD

**Issue by mcmire** [MetaMask/create-release-branch#141]
When this tool is run against a monorepo using Yarn Modern and bumps the version of a particular package, a Yarn constraint in the monorepo (such as the one that `core` has) may demand that for other packages which have that package as a dependency, the version range of that dependency is changed to match the version of the package. This problem can be solved by running `yarn constraints --fix && yarn` after creating the release branch, but it would be nice if this were run automatically so that lint does not fail when pushing the release branch.

The fact that this does not run automatically is an inconvenience on its own, but it also creates a real problem. If the major version of a package is bumped, it may cause a major bump in a dependent package. This means that in this situation, both the dependency and the dependent would need to be released together. Ordinarily, this tool would catch this scenario and make sure this happens, but if it doesn't change the dependent package automatically and the user needs to do it manually, then the tool can't catch that scenario. The bottom line is that users may be forgetting to release companion packages together. If we run `yarn constraints --fix && yarn` after bumping packages, though, `validateReleaseSpecification` can check for this.

**Comment by desi** [comment]
@mcmire after discussion in refinement we need to revisit this. Not ready for dev.

**Comment by desi** [comment]
Closing as duplicate
