### ISSUE TITLE
Remove error shown when omitting changed packages from release spec

### ISSUE THREAD

**Issue by mcmire** [MetaMask/create-release-branch#92]
In order to support partial releases of a monorepo — that is, the ability to publish a subset of publishable packages within a release — we need to allow users to omit packages from the release spec that have changes since their previous release.

To do this, we need to:

- Remove the check that runs when a version is not specified for a package that is checked
- Remove the error that is thrown when that happens
- Remove `intentionally-skip` as a possible version specifier for the release spec

Part of https://github.com/MetaMask/core/issues/1539.

**Comment by cryptodev-2s** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Shared-Libraries-621e46b4d7103800171d1b02/issues/MetaMask/create-release-branch/92?planning-poker) with Zenhub @mikesposito @mcmire @Gudahtt
